Datasets:
  - Identifier: S2_T30UVG
    Title: "S2 Auchencoth All Vars"
    FileSystem: s3
    Endpoint: 'https://stuos4epdata01.blob.core.windows.net'
    Path: '/zarr-cubes/Auchencorth_T30UVG_all_stack.zarr'
    Anonymous: true
    TimeSeriesDataset: S2_T30UVG_Timeseries
    Style: default0

  - Identifier: S2_T30VVJ
    Title: "S2 Cairngorms All Vars"
    FileSystem: s3
    Endpoint: 'https://stuos4epdata01.blob.core.windows.net'
    Path: '/zarr-cubes/Cairngorms_T30VVJ_all_stack.zarr'
    Anonymous: true
    TimeSeriesDataset: S2_T30VVJ_Timeseries
    Style: default0


Styles:
  - Identifier: default0
    ColorMappings:
      NDVI:
        ColorBar: "BrBG"
        ValueRange: [-1, 1]
